### ISSUE TITLE
SEO optimization and usage of CSS

### ISSUE THREAD

**Issue by abhirock1998** [koders-in/Payments-Frontend#2]
- [x] trying to avoid using inline CSS 
- [x] Use SVG or web images
- [x] Use CSS variable
- [x] Add meta tags for SEO in the index.html file
- [x] remove unused font family files from the fonts folder

**Comment by mstomar698** [comment]
Can u assign this issue to me?

**Comment by 1stdevfriend** [comment]
Sure.

**Comment by mstomar698** [comment]
> Sure.

thanks! I will have a PR in a day or two...
